_format_version: "1.1"

services:
  # service-1
- name: service-1
  url: http://192.168.2.9:8080
  routes:
  - name: service-1
    paths:
    - /service-1

  # auth-service
- name: auth
  url: http://192.168.2.9:8084
  routes:
  - name: auth
    paths:
    - /auth